version: '3.7'
services:
  alarm-online2:
    image: image-alarm-online
    container_name: container-alarm-online2
    build: .
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alarm-online2.rule=Host(`thomas-chateau.net`) && PathPrefix(`/alarm-online`)"
#     - "traefik.http.routers.alarm-online.rule=Host(`thomas-chateau.net`)"
      - "traefik.http.routers.alarm-online2.entrypoints=web"
      - "traefik.docker.network=traefik"
#     - "traefik.http.routers.alarm-online.service=alarm-online"
#     - "traefik.http.services.alarm-online.loadbalancer.server.port=4999"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: vps-traefik_webgateway 

