version: '3.7'
services:
  alarm-online2:
    image: image-alarm-online2
    container_name: container-alarm-online2
    build: .
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alarm-online.entrypoints=web"
      - "traefik.http.routers.alarm-online.rule=Host(`thomas-chateau.net`) && PathPrefix(`/alarm-online`)"
      - "traefik.docker.network=traefik"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: vps-traefik_webgateway