version: '3.7'
services:
  alarm-online:
    image: image-alarm-online
    container_name: container-alarm-online
    build: .
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`thomas-chateau.net`) && (PathPrefix(`/alarm-online`)"
      - "traefik.http.routers.catapp.entrypoints=web"
      - "traefik.http.routers.catapp.service=catapp"
      - "traefik.http.services.catapp.loadbalancer.server.port=5000"
