version: '3.7'
services:
  alarm-online:
    image: image-alarm-online
    container_name: container-alarm-online
    build: .
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alarm-online.rule=Host(`51.75.127.63`)"
      - "traefik.http.routers.alarm-online.entrypoints=web"
      - "traefik.http.routers.alarm-online.service=alarm-online"
      - "traefik.http.services.alarm-online.loadbalancer.server.port=4999"
